global using CommunityToolkit.Maui;
global using Microsoft.Extensions.Logging;
global using PizzaMAUI.Models;
global using PizzaMAUI.Pages;
global using PizzaMAUI.Services;
global using PizzaMAUI.ViewModels;
global using System.Collections.ObjectModel;
global using CommunityToolkit.Mvvm.Input;
global using CommunityToolkit.Mvvm.ComponentModel;
